### ISSUE TITLE
Add a search API to Minerva

### ISSUE THREAD

**Issue by goodb** [geneontology/minerva#230]
Add a search API to Minerva - drive front page and [Annotation Review Tool](http://noctua-dev.berkeleybop.org/workbench/noctua-annotation-review/)  which might be the same thing.  

## Endpoint

**api/search**

- Default sorting is date DESC (recent models)
- Default n models per page
- All the parameters are optional and by default it should bring recent n models with 'Date DESC'

## Parameters

| Parameter                          | Format             | Comments                                                                                           |
| ---------------------------------- | ------------------ | -------------------------------------------------------------------------------------------------- |
| **gps** (optional)                 | list\<gp>          | A list of one or more gps in a model (AND operator)                                                |
| **goterms**  (optional)            | list\<goterm>      | A list of one or more GO terms in a model (AND operator)                                           |
| **pmids** (optional)               | list\<pmid>        | A list of one or more pmids in a model (AND operator)                                              |
| **taxa** (optional)                | list\<taxon>       | A list of one or more taxon                                                                        |
| Model Meta                         |
| **title** (optional)               | string             | Partial String (contains) so it works like the current landing page                                |
| **states** (optional)              | list\<state>       | A list of one or more model states 'development, production, closed, review, delete' (OR operator) |
| **contributors** (optional)        | list\<contributor> | A list of one or more contributors in a model (AND operator)                                       |
| **groups** (optional)              | list\<group>       | A list of one or more groups(provided by) in a model (AND operator)                                |
| **date** (optional)                | date               | model date                                                                                        |
| Pagination (optional, none or all) |
| **page**                           | int                | Page number                                                                                        |
| **offset**                         | int                | Page Offset                                                                                        |
| **limit**                          | int                | Page Size                                                                                          |

## Return

**total count matched models** for progressive pagination when one needs second page 

A list of

| Parameter              | Format             | Comments                                              |
| ---------------------- | ------------------ | ----------------------------------------------------- |
| **model id**           | iri                | A model id                                            |
| **matched nodes**      | list\<iri>         | A list of one or more matched individual nodes        |
| Model Meta             |
| **model title**        | string             | A model title, first title annotation is fine if many |
| **model state**        | string             | A model's state                                       |
| **model date**         | string             | A model modified date                                 |
| **model contributors** | List\<contributor> | A list of model's contributors                        |
| **model groups**       | List\<groups>      | A list of model's groups (provided by)                |

**Implementation**: 
a sparql query composer
response object model

**Web Access**- This is either accessed by a new Jersey service (e.g. /search like [this sparql endpoint](https://github.com/geneontology/minerva/blob/master/minerva-server/src/main/java/org/geneontology/minerva/server/handler/SPARQLHandler.java)) or a new  handler for current route /M3Batch (using the main existing protocol)

**Comment by goodb** [comment]
Need conversation with @cmungall @kltm @balhoff to resolve question about how the service will be accessed.

**Comment by goodb** [comment]
@tmushayahama I'm looking at the contributors and groups query.  Do you really need that to be an AND operator ?  Its hard to imagine users really needing or wanting that level of specificity on that query.  I would imagine that an OR would actually be more in line with what they would want to see happen.  

Let me know.  Also.  On date.  a) what specific format will this arrive in - e.g. string YY/MM/dd and b) is this supposed to be an equals, >, or < request ?

**Comment by goodb** [comment]
@tmushayahama @kltm this branch https://github.com/geneontology/minerva/tree/api_hack_1 now contains a service that implements the above requested API with some differences as follows:

- The parameter names are in singular form, even for potential lists, e.g. the parameter for gene product ids is "gp", not "gps" and "goterm" not "goterms", etc.  
- When sending lists, repeat the parameter in the query e.g. http://127.0.0.1:6800/search/?gp=http://identifiers.org/wormbase/WBGene00002246&gp=http://identifiers.org/wormbase/WBGene00002247&gp=http://identifiers.org/wormbase/WBGene00002248  
- I have not implemented taxa yet.  This requires gaining access to information that is not currently stored in the Minerva blazegraph and will thus require further development.  I am curious how important this really is to users. 
- For contributors and groups, the search is currently doing an OR query rather than the requested AND.  This is my intuition about how users would prefer the interface to work.  If wrong, let me know and I will fix.  
- The date parameter will produce all models more recent than the specified date
- I did not add a 'Page' parameter.  Paging can be achieved by iterated requests using the offset and limit parameters.  This lets the client control how large the page blocks are.  e.g. to iterate through results 2 at a time, query like this, in order:
http://127.0.0.1:6800/search/?date=2019-03-06&offset=0&limit=2
http://127.0.0.1:6800/search/?date=2019-03-06&offset=2&limit=2
etc.
you will get the same thing you would get from the following request, but in two steps instead of one.
http://127.0.0.1:6800/search/?date=2019-03-06&offset=0&limit=4
- As it stands at this moment, it is expecting Get requests.  If its useful I will add the equivalent Post.  
- Parameters may be combined arbitrarily and will result in an AND query that combines them.  
- Exact parameter list: gp, goterm, pmid, title, state, contributor, group, date, offset, limit
- endpoint /search  which I have been accessing at :6800 - not sure what the root is if passing through barista on the way.  ping @kltm on that.  
- the 'query_match' map element in the response indicates what nodes in the model matched the query terms.  When the query parameters are at the model level (e.g. title, group) this will be empty

I think that is it.  Right now there is absolutely no error handling or other such niceties.  But, it would be an appropriate time for client developers to take it for a spin and see if it meets their needs.  

A response block looks like this: 
`{
  "n": 2,
  "models": [
    {
      "id": "gomodel:5ce58dde00001253",
      "date": "2019-06-26",
      "title": "test same BP",
      "state": "development",
      "contributors": [
        "http://orcid.org/0000-0002-1706-4196",
        "http://orcid.org/0000-0003-1813-6857"
      ],
      "groups": [
        "http://www.wormbase.org",
        "http://geneontology.org"
      ],
      "query_match": {
        "http://identifiers.org/wormbase/WBGene00002246": [
          "http://model.geneontology.org/5ce58dde00001253/5ce58dde00001259"
        ]
      }
    },
    {
      "id": "gomodel:5941cdbd00000002",
      "date": "2019-03-05",
      "title": "LAG-2 - GLP-1 Signaling in C. elegans germline proliferation - Notch signaling part 1",
      "state": "development",
      "contributors": [
        "http://orcid.org/0000-0002-1706-4196",
        "http://orcid.org/0000-0001-7476-6306"
      ],
      "groups": [
        "http://informatics.jax.org",
        "http://www.wormbase.org"
      ],
      "query_match": {
        "http://identifiers.org/wormbase/WBGene00002246": [
          "http://model.geneontology.org/5941cdbd00000002/5941cdbd00000003"
        ]
      }
    }
  ]
}`

**Comment by kltm** [comment]
Now being blocked by my https://github.com/geneontology/noctua/issues/619

**Comment by goodb** [comment]
(and note it currently wants URIs for gene products and goterms) if clients need it, we can add support for curies.

**Comment by kltm** [comment]
@goodb I've tried switching `noctua-dev` over to your `api_hack_1` branch, but am running into trouble. For all queries, e.g.:

http "http://wok.lbl.gov:6800/search"
http "http://wok.lbl.gov:6800/search?date=2019-03-06&offset=0&limit=2"

I get a return of 

```http
HTTP/1.1 500 Request failed.
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 290
Content-Type: text/html; charset=ISO-8859-1
Date: Wed, 03 Jul 2019 23:23:17 GMT
Server: Jetty(9.2.z-SNAPSHOT)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /search. Reason:
<pre>    Request failed.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

likely caused by a timeout in minerva 

```
...
2019-07-03 16:25:18,608 WARN  (HttpChannel:483) Could not send response error 500: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: org.openrdf.query.QueryInterruptedException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.bigdata.bop.engine.QueryTimeoutException: Query deadline is expired.
2019-07-03 16:25:18,681 INFO  (LoggingApplicationEventListener:44) Request 20 started.
```

I guess a side request would be that exceptions like this are caught so that clients can get a little more information without have to fully parse (like other errors that minerva sends). More importantly would be that I'm guessing that this is timing out as there are too many models to handle in its (10s?) timeout window?

**Comment by kltm** [comment]
Discussion with @goodb , while slowness is being looked at, I can continue with faster queries such as:
 /search/?gp=http://identifiers.org/wormbase/WBGene00002246&offset=0&limit=2

**Comment by goodb** [comment]
@kltm I think I fixed slowness.  Some sparql tuning and all queries are now working very fast on my laptop against the whole collection in noctua-dev, including text queries.  I also added some exception handling and reporting; and returning the constructed sparql for debugging purposes.

**Comment by tmushayahama** [comment]
Have added this issue https://github.com/geneontology/minerva/issues/235

**Comment by goodb** [comment]
I believe this issue can be closed.  Unless @tmushayahama is missing anything?

**Comment by tmushayahama** [comment]
@goodb  I think species and title is still missing. Also I will let @vanaukenk close it after testing ART.

**Comment by goodb** [comment]
@tmushayahama title and model id are in the response - see e.g. http://wok.lbl.gov:6800/search?date=2019-03-06&offset=0&limit=2  

Species is not likely to happen in the near term unless we get a high priority push from PIs.  This is because it is the only parameter that is not currently present to access in the Minerva blazegraph that stores the models.  We can figure it out, but a good solution probably requires some broader changes that touch things outside of what the API deals with (e.g. tagging models on save with species information).

**Comment by lpalbou** [comment]
@goodb is it because neo was not loaded in the minerva triplestore (https://github.com/geneontology/minerva/issues/226), hence you have no access to the taxon of a gene and hence can not perform a species search ?

**Comment by goodb** [comment]
Correct, no ontologies are loaded into the minerva blazegraph triplestore.

**Comment by goodb** [comment]
@tmushayahama FYI, when the latest PR is merged, I believe the search api results will be sorted based on date.

**Comment by goodb** [comment]
Note to myself to check - when a user is added to the search, make sure the other users associated with returned models still get returned..

**Comment by goodb** [comment]
Going to close this.  Search API exists, lets move on to more specific tickets now.  Documentation consolidated at https://github.com/geneontology/minerva/wiki/Minerva-Model-Search-API

**Comment by tmushayahama** [comment]
@goodb @lpalbou  where should I ask or report api specific questions from the wiki?

Param &expanded means any subtype for a term? So far everything is expanded by default and the param is not yet in use, is that correct? From the returned Sparql. In this case

I tested the extreme case and it is timing out. 

### Test
Search using Root Molecular Function
http://barista-dev.berkeleybop.org/search?offset=0&limit=50&term=GO:0003674 or 
http://barista-dev.berkeleybop.org/search?offset=0&limit=50&term=GO:0003674&count
or http://barista-dev.berkeleybop.org/search?offset=0&limit=50&term=GO:0003674&expand

### Results
Query Timeout Exception
![image](https://user-images.githubusercontent.com/2273929/78091231-21025d80-7381-11ea-8d3a-64b788f08ee7.png)

Search to get the full response, it's large to post here

### Thoughts
@lpalbou @goodb  I can use UI tricks to slow down user, like have a toggle button for exact term and subtypes controlled by &expand param. Or a limit to a depth of subtypes or prompt a user to select reasonable amount of terms from subtypes.

**Comment by goodb** [comment]
@tmushayahama this should be over on:  https://github.com/geneontology/minerva/issues/291  - will respond there.
